title: Yuzhuo Chen's Homepage
page-top-title: Yuzhuo Chen
top-section-bg-text: Stay Curious, Stay Patient
# home-subtitle: Yuzhuo Chen&ensp;|&ensp;Suchenl
home-subtitle: Yuzhuo Chen
copyright-text: '&copy; Yuzhuo Chen 2025. All Rights Reserved.'
